on: 
  pull_request:
    types: [closed]
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Deploy for Host
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.server_ssh_key }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.FTP_HOST }}
          REMOTE_USER: ${{ secrets.FTP_USER }}
          TARGET: ${{ secrets.FTP_TARGET }}
          EXCLUDE: "/dist/, /node_modules/, /vendor/"